import './globals.css'
import { SidebarWrapper } from '@/components/sidebar-wrapper';
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'react-bootstrap-typeahead/css/Typeahead.css';
import 'react-bootstrap-typeahead/css/Typeahead.bs5.css';
import Script from 'next/script';
import Head from 'next/head';

import { AppProvider } from '@/providers/app-provider';
import { NavigationTabs } from '@/components/navigation-tabs';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children }:{children:React.ReactNode}) {

  return (
    <html lang="en" className="dark bg-background text-foreground">
      <body>
        <AppProvider>
          <SidebarWrapper>
            <main className="mt-4 h-full w-full overflow-visible">
              <div className="flex h-[90%] w-full flex-col gap-4 p-6 rounded-medium border-small border-divider">
                {children}
                <NavigationTabs />
                
              </div>
            </main>
          </SidebarWrapper>
        </AppProvider>
      </body>
    </html>
  )
}
